{{/*
# Copyright 2020-present Open Networking Foundation

# SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.config.gnbsim.deploy }}
{{- if not .Values.config.useExistingConfigMap }}
{{- $config := index .Values.config "gnbsim" }}
{{- $gnbconf := index .Values.config.gnbsim.yamlCfgFiles "gnb.conf" }}
{{- $configuration := index $gnbconf "configuration" }}

{{- if not (hasKey $configuration "singleInterface") -}}
{{- $_ := .Values.config.gnbsim.singleInterface | set $configuration "singleInterface" -}}
{{- end }}
{{- $_ := .Values.config.gnbsim.networkTopo | set $configuration "networkTopo" -}}
{{- end }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gnbsim
  labels:
{{ tuple "gnbsim" . | include "5g-ransim-plane.metadata_labels" | indent 4 }}
data:
  gnbsim-run.sh: |
{{ tuple "bin/_gnbsim-run.sh.tpl" . | include "5g-ransim-plane.template" | indent 4 }}
{{- range $key, $value := .Values.config.gnbsim.yamlCfgFiles }}
  {{ $key }}: |-
{{ toYaml $value | indent 4 }}
{{- end }}
{{- end }}
